### PR TITLE
Release Version 7.4

### PR DESCRIPTION
**Pull request by insidegui**
@allenhumphreys mind taking this for a spin before we ship it? (`Releases/WWDC_latest.zip` has the notarized build)

### CODE REVIEW

**Comment by allenhumphreys** [comment]
Unfortunately I won't be able to get to it until this evening, and if that doesn't happen, it'll be Sunday/Monday time frame :-(

**Comment by insidegui** [comment]
Had a dirty branch and ended up introducing unintended experimental code into this, will revert then open a new PR 😅

**Comment by insidegui** [comment]
All good now (presumably 😅)

**Comment by insidegui** [comment]
[Already available in releases](https://github.com/insidegui/WWDC/releases/tag/7.4-release), will wait a moment before merging this, which ships the auto-update.

**Pull request merged**
