### PR TITLE
Update to README

### PR DESCRIPTION
**Pull request by 9race**
Minor changes to fix spelling and improve wording

### CODE REVIEW

**Comment by insidegui** [comment]
I'm not going to accept this because it seems like the type of PR only made to earn "points" by being listed as a contributor. Feel free to contribute again in the future with meaningful changes and a real profile.

**Comment by 9race** [comment]
Hi, I just joined and am brand new to the GitHub community. I've never created a pull request before, and after watching a YouTube tutorial I decided to make a few basic changes to this project just to see how the process works from start to finish. I do not intend to keep on doing this in the future, this was merely a Hello World" PR.

**Comment by insidegui** [comment]
@9race I understand. Sorry for assuming bad intent, it's just that this type of PR is often opened by people as a sort of "SPAM" to be listed as contributors to popular projects. I suggest looking for simple bug fixes you can address, most repositories have a "Good First Issue" tag attached to issues, that might be a great place to get started.

**Comment by 9race** [comment]
No worries! I would do the same thing if I were in your shoes. And thank you for the advice, I'll keep it in mind.

**Pull request closed without merging**
