### PR TITLE
Saves and restores filter state across launches

### PR DESCRIPTION
**Pull request by allenhumphreys**
I don't think this PR is ready, but I'm opening it to get some feedback. My implementation is simple in it's approach, yet effective. In ObjC I would've just encoded the object graphs by adopting the NSCoding protocol. But that isn't very Swifty and I didn't think it prudent to make all of the filter types objects.

Suggestions welcome. Nothing is too small.

### CODE REVIEW

**Comment by bcmn** [comment]
Would it make sense to implement this later, when we can utilise Swift 4's Codable protocol? I don't think we can commit to a timeline, but it's definitely our intention to migrate, so manually implementing, maintaining & potentially replacing this on migration might be an odd choice.

@insidegui for thoughts.

**Comment by bcmn** [comment]
I would really like to see filters persist, but I was giving it some thought after #268 and I feel that from a purely UX-y view we should consider making sure it's obvious when filters are in action, especially if we intend to make them persist. This might really ought to be a separate issue from the tech details above, though.

A couple of unimaginative or maybe even crude ways of achieving this could be that we highlight the filter menu button in the blue accent colour, or force the filter menu open if the app is started and any filters were active and have persisted.

**Comment by allenhumphreys** [comment]
The `Codable` protocol would definitely make things easier. In the several contexts I've tested Swift 4 migration, it has been really painless. I'm sure we want to wait until Xcode 9 is fully released, though. 

This work definitely has some things that are outright fixes, though, so I can definitely decouple those from the information storage to ensure those get applied either way. 

Something I can do to simplify maintenance and later adoption of Codable is to brute force and centralize the data storage and make it so the code that restores the state is given data in the format the Codable implementation will produce, which is likely a dictionary containing actual `FilterTypes`. 

As for making it more clear that filters are active. Maybe adding a "clear" button would help?

Also, this branch does force the filters menu open if filters are still active on launch.

**Comment by insidegui** [comment]
> Something I can do to simplify maintenance and later adoption of Codable is to brute force and centralize the data storage and make it so the code that restores the state is given data in the format the Codable implementation will produce, which is likely a dictionary containing actual FilterTypes.

This would be great. We can have the functionality right away while we wait for Xcode 9 to be stable and migrate easily when it does. We have at least two months before that happens so I think it's worth it.

> Maybe adding a "clear" button would help?

I agree. @VicenteBorrell suggested we add "clear" options to each dropdown menu but that would make the code a lot more complex and wouldn't be easy for the user to clear everything.

Here's what I think about clearing the filters: 

- If you're using the search field, pressing ESC or clicking the "X" button will clear the textual search filter, so that's not an issue (it's already easy to do)

- If you're using the other filters, maybe we could clear them if the filter button is pressed and the filters collapse. As a way to make the action less destructive and avoid accidental "data loss", reopening the filters by pressing the filter button immediately after collapsing could reactivate the previous filters

**Comment by bcmn** [comment]
> As for making it more clear that filters are active. Maybe adding a "clear" button would help?

I would suggest this is different functionality. The enabled/disable state of one button isn't a particularly noticeable way of depicting "filters are enabled", especially as it would seem there isn't a clear position this button could be added into without being in the collapsible filters menu. 

Separately though, this seems like something we should have. Perhaps open an issue, & we can get design input on where this should go? I agree though, Gui -- a single button makes far more sense for this functionality.

> maybe we could clear them if the filter button is pressed and the filters collapse.

I think this would be very odd behaviour to interfact with in practice. I think it's fairly instinctive to hide the visual clutter of the filter box once you've found the collection of things you want, especially amongst the modern hyper-anti-clutter Apple interfaces. My use case often involves filtering videos to a certain set of filters (e.g. Year, downloaded, favourites) for long periods of time, & having to leave the filter menu open for potentially hours seems like it would be wasting a significant chunk of screen real estate that could be better utilised by the sidebar table view.

> Also, this branch does force the filters menu open if filters are still active on launch.

Awesome. 😊 I didn't get time to test the branch, & I must've missed this when I looked over the changes. This seems like a solution that's more than good enough for now while we discuss any other indications we want to add.

**Comment by insidegui** [comment]
> I think this would be very odd behaviour to interact with in practice. I think it's fairly instinctive to hide the visual clutter of the filter box once you've found the collection of things you want, especially amongst the modern hyper-anti-clutter Apple interfaces. Furthermore, personally, my use case often involves filtering videos to a certain set of filters (e.g. Year, downloaded, favourites) for long periods of time, & having to leave the filter menu open for potentially hours seems like it would be wasting a significant chunk of screen real estate on unchanging user input that could be better utilised by the sidebar table view.

Yeah that makes sense. The collapsed/expanded state should not affect whether the filters are active.

**Comment by insidegui** [comment]
@allenhumphreys Can you make the changes you mentioned that would make it easier for us to migrate to Swift 4 `Codable` later, before I merge this?

**Comment by allenhumphreys** [comment]
Absolutely, it'll be a couple of days, I need to spin up a playground and test Codable in Xcode to fully understand what my implementation should look like. Thanks for the input.

**Comment by allenhumphreys** [comment]
So, it looks like `Codable` isn't the magic bullet we are all hoping for. I'm hitting a wall with the heterogenous array of `[FilterType]`. I've been trying to use either JSON or Plist encoders to produce some kind of output with dismal results. The provided encoders don't have a mechanism to mix types in a collection. It's also impossible to effectively implement your own conformance and the synthesized conformance can't handle `NSPredicate`. Writing my own encoder and decoder seems to be a non-trivial task judging by the implementations of `JSONEncoder` and `PropertyListEncoder`. I have a [playground](https://github.com/allenhumphreys/swift-codable) setup with the required types, if someone else would like to try to help me understand this seemingly glaring limitation.

**Comment by insidegui** [comment]
I haven't looked into that myself, but I believe your conclusions are correct.

Since apparently we can't easily migrate to `Codable`, is there anything else you want to do in this PR or can we merge it now?

**Comment by allenhumphreys** [comment]
I'd like to do some cleanup before merging.

**Comment by insidegui** [comment]
Great! Let me know when you're done.

**Comment by allenhumphreys** [comment]
I cleaned up, squashed, and rebased. 

The JSON representing the filtering state across both tabs is stored as a string in the preferences plist. This is the basic information that it contains:

```
{
  "WWDC.MainWindowTab.videos" : {
    "focus" : {
      "options" : [
        {
          "value" : "iOS",
          "title" : "iOS"
        },
        {
          "value" : "macOS",
          "title" : "macOS"
        },
        {
          "value" : "tvOS",
          "title" : "tvOS"
        },
        {
          "value" : "watchOS",
          "title" : "watchOS"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "text" : {
      "value" : ""
    },
    "track" : {
      "options" : [
        {
          "value" : "Featured",
          "title" : "Featured"
        },
        {
          "value" : "Media",
          "title" : "Media"
        },
        {
          "value" : "Developer Tools",
          "title" : "Developer Tools"
        },
        {
          "value" : "Graphics and Games",
          "title" : "Graphics and Games"
        },
        {
          "value" : "System Frameworks",
          "title" : "System Frameworks"
        },
        {
          "value" : "App Frameworks",
          "title" : "App Frameworks"
        },
        {
          "value" : "Design",
          "title" : "Design"
        },
        {
          "value" : "Distribution",
          "title" : "Distribution"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "isUnwatched" : {
      "isOn" : false
    },
    "event" : {
      "options" : [
        {
          "value" : "wwdc2017",
          "title" : "WWDC 2017"
        },
        {
          "value" : "wwdc2016",
          "title" : "WWDC 2016"
        },
        {
          "value" : "wwdc2015",
          "title" : "WWDC 2015"
        },
        {
          "value" : "wwdc2014",
          "title" : "WWDC 2014"
        },
        {
          "value" : "wwdc2013",
          "title" : "WWDC 2013"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "isDownloaded" : {
      "isOn" : false
    },
    "isFavorite" : {
      "isOn" : false
    }
  },
  "WWDC.MainWindowTab.schedule" : {
    "focus" : {
      "options" : [
        {
          "value" : "iOS",
          "title" : "iOS"
        },
        {
          "value" : "macOS",
          "title" : "macOS"
        },
        {
          "value" : "tvOS",
          "title" : "tvOS"
        },
        {
          "value" : "watchOS",
          "title" : "watchOS"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "text" : {
      "value" : ""
    },
    "track" : {
      "options" : [
        {
          "value" : "Featured",
          "title" : "Featured"
        },
        {
          "value" : "Media",
          "title" : "Media"
        },
        {
          "value" : "Developer Tools",
          "title" : "Developer Tools"
        },
        {
          "value" : "Graphics and Games",
          "title" : "Graphics and Games"
        },
        {
          "value" : "System Frameworks",
          "title" : "System Frameworks"
        },
        {
          "value" : "App Frameworks",
          "title" : "App Frameworks"
        },
        {
          "value" : "Design",
          "title" : "Design"
        },
        {
          "value" : "Distribution",
          "title" : "Distribution"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "isUnwatched" : {
      "isOn" : false
    },
    "event" : {
      "options" : [
        {
          "value" : "Session",
          "title" : "Sessions"
        },
        {
          "value" : "Session",
          "title" : "Labs and Others"
        }
      ],
      "selectedOptions" : [

      ]
    },
    "isDownloaded" : {
      "isOn" : false
    },
    "isFavorite" : {
      "isOn" : false
    }
  }
}
```

One final change I could make, if desired, is to exclude all of the information if the filters are all off. Otherwise, in its current form, the JSON is always created.

**Comment by allenhumphreys** [comment]
Oh shoot, I just realized I don't need to store the current options, just the selected ones! That was an artifact of my earlier design.

**Comment by insidegui** [comment]
Yeah I was just going to mention we don't have to store the options haha.

So, is this done? :)

**Comment by allenhumphreys** [comment]
It's good to go, imo.

**Pull request merged**
