### PR TITLE
Enabled database compression on launch

### PR DESCRIPTION
**Pull request by insidegui**
This aims to solve what's described in #580 

I haven't tested with a really huge database file, but with a reasonably large database file (~300MB), the compression occurred at launch with no noticeable impact to the user experience.

A defaults flag was introduced (`WWDCDisableDatabaseCompression`) to disable the feature, just in case.

### CODE REVIEW

**Comment by mackuba** [comment]
Should I try it on my 38-gig file (I haven't reset it yet)? Should it help in this case?

**Comment by insidegui** [comment]
@mackuba That would be great! Thank you

**Comment by mackuba** [comment]
Looks like it worked! I tried it last night, and at first it said the database was a few hundred MB, but I've realized it was running in debug mode and pointing to a different directory, then I rerun it in release mode and it just said `Total bytes: 0`… and now I've just launched it again and it seems it has compacted it to a few hundred MB:

Before:

Screen Shot 2020-05-30 at 01 50 06

After:

Screen Shot 2020-05-30 at 19 11 27

**Comment by insidegui** [comment]
Awesome! Thanks for taking the time to test this @mackuba

**Pull request merged**
