### PR TITLE
Issue 21: search through transcripts

### PR DESCRIPTION
**Pull request by art-divin**
Current implementation doesn't sort according to number/quality of matches, but I think it works relatively good for initial implementation

### CODE REVIEW

**Comment by insidegui** [comment]
- The search takes a considerable amount of time
- Multiple words don't work (try searching for "customer sat")
- I tried searching using multiple qualifiers and including "transcript:" but only "transcript:" was considered (try searching "year:2013 transcript:animation")

I really don't think this feature is worth our time, It makes the search too broad and complicated.

**Comment by art-divin** [comment]
@insidegui thanks for the feedback.

Regarding "worthness", I agree that it creates a new format of the search and adds dependency on another endpoint, which doesn't necessarily work fast enough.
However, while developing a lot of iOS 8 stuff during June-December period of 2014, I found myself browsing through WWDC videos just trying to find where exactly did I hear something about some specific new API during actual session in June.

I think that if to fix issue 2&3, the time issue is not so important since this kind of functionality is very useful.

**Comment by insidegui** [comment]
What if we downloaded ASCIWWDC's entire catalog to make a local index? That would make the search a lot faster and maybe allow us to disable "sendsWholeSearchString".

We could download the transcripts for every video we have on the first launch, store them locally (maybe using plists, idk, we may need something like Core Data for this) and every now and then check to see if there are updates.

Later when I add a preferences window (I'll do that soon), we can have a preference to disable transcript search for those who don't want/need It.

**Comment by art-divin** [comment]
@insidegui makes sense, I agree that local search should be implemented even for transcripts.
However, this implies implementing whole other background service for fetching transcripts one-by-one, isn't it?

I think that this PR can be closed without merging, and discussion should be moved in #issue #21

**Comment by insidegui** [comment]
Yup

**Pull request closed without merging**
