### PR TITLE
Improve constancy between the tableView's NSMenu and the VideoDetailsViewController

### PR DESCRIPTION
**Pull request by SoneeJohn**
- Videos from 2013 and above will be evaluated
- if a session isScheduled then both the `downloadMenuItem` and
`removeDownloadMenuItem` will be disabled

else the menu items are evaluated based on whether or not it has been
downloaded
- any other session (pre-2013 ) the menu items are disabled

Note: I haven’t throughly tested this but, it works fine so far.

#136

### CODE REVIEW

**Comment by insidegui** [comment]
Thanks! Can you please remind me to merge this after next week? I won't me merging any PRs until after WWDC because any change to the app I'm making right now is being very thoroughly tested in various circumstances to make sure everyone can watch the sessions live without major issues :)

**Comment by SoneeJohn** [comment]
@insidegui Sure no problem 😊

**Comment by bre7** [comment]
Hi @SoneeJohn, I noticed the same things you did and wanted to add some details to your PR. Would you mind adding the same eval for "Mark as Watched"/"Mark as Unwatched" and "Add to Favorites"/"Remove from Favorites" ?

**Comment by insidegui** [comment]
Can you please make the following changes before I merge:

- Move the `NSMenuDelegate` conformance to an extension instead of declaring It directly on the view controller class
- Use `guard` and early return instead of nested if statements
- Not connect menu items directly to the controller with outlets, give each menu item a tag and validate based on the tag (you can use an enum to encapsulate the meaning of each tag:

```
    private enum MenuItemTags: Int {
        case Download = 1001
        case RemoveDownload = 1002
    }
```

**Comment by SoneeJohn** [comment]
@insidegui Quick question because I'm new to Swift. If I move `NSMenuDelegate` from the view controller into an extension how will assign the `tableView`'s `NSMenu`'s delegate so that I can be notified when the menu is about to open? I was thinking instead to do this: 

```
override func validateMenuItem(menuItem: NSMenuItem) -> Bool{
        
//Validate the items
        return false
        
    }
```

**Comment by SoneeJohn** [comment]
Hi @bre7 I made the changes to validate those items as well.

**Comment by insidegui** [comment]
You can just declare an extension on `VideosViewController ` which conforms to `NSMenuDelegate` and implement the delegate methods in there. The assignment to the table view can still be done on the main class.

```swift
extension VideosViewController: NSMenuDelegate {
    // Implement NSMenuDelegate methods here
}
```

You can also move your enum into this extension to make the code a little cleaner ;)

**Comment by SoneeJohn** [comment]
@insidegui Thanks :). I ended up using `func validateMenuItem(menuItem: NSMenuItem) -> Bool`, take a look and tell me what you think.

**Pull request merged**
