### PR TITLE
Feature #456: Show Time Preview when hovering over Timeline

### PR DESCRIPTION
**Pull request by dinesharjani**
This has been implemented in a similar way to how we show the timestamp for the user's annotations in the timeline.

### CODE REVIEW

**Comment by insidegui** [comment]
Implementation looks good to me, let's decide on [that behavior](
https://github.com/insidegui/WWDC/issues/456#issuecomment-410346598) and implement our decision before merging 😉

**Comment by dinesharjani** [comment]
@allenhumphreys @VicenteBorrell @bcmn  let us know your thoughts after playing with the branch on what to do with the preview when it's close to the timeline's timestamp labels

**Comment by insidegui** [comment]
@dinesharjani I just noticed that the text looks blurry on my retina MBP, I think you need to set some property on the text layer for it to correctly render at 2x

screen shot 2018-08-04 at 20 08 02

**Comment by insidegui** [comment]
Also, when dragging an annotation out (to delete it), the current time indicator stays visible until the annotation is released, I think it should hide as soon as it starts being dragged. Another issue is that if you drag an annotation and then cancel the drag by dropping it at the same position, then move the mouse cursor out of the player view, the floating time indicator will stay visible until you move the mouse over the player again.

annotationissue1

annotationissue2

**Comment by dinesharjani** [comment]
Wow! Nice catches @insidegui !

I'll work on fixing these as soon as I can. Thanks a lot for the help in getting this feature working well !!

**Comment by allenhumphreys** [comment]
This is looking good overall. The time preview is overlapping the time labels for me though, 
screen shot 2018-08-10 at 11 59 10 am

**Comment by dinesharjani** [comment]
Sorry for the delay - I was busy with some interviews.

**Comment by dinesharjani** [comment]
@insidegui @allenhumphreys if this solution doesn't seem good enough, I can further improve this by animating the current and remaining timestamps invisible whenever the user scrubs on both edges of the playback bar. I'm also open to other ideas, of course.

**Comment by insidegui** [comment]
I haven't been able to test the latest implementation yet, I'll let you know.

**Comment by insidegui** [comment]
Edge avoidance looks good!

One last nitpick: when transitioning from hovering over the timeline to hovering over an annotation, the two timestamps displayed fade at the same time and it looks janky. Could we just hide the timeline one without animation to avoid that issue?

Thanks a lot for your work on this @dinesharjani !

**Comment by allenhumphreys** [comment]
I think everyone is really going to love this feature! And I agree about the annotation time jankiness!

**Comment by dinesharjani** [comment]
I think it's better now, let me know!

**Comment by insidegui** [comment]
Great work @dinesharjani

**Pull request merged**
