### PR TITLE
New special event and get-together images

### PR DESCRIPTION
**Pull request by SoneeJohn**
The current images for special events and get-togther events are a bit hard to see. Let me know what you think of my changes 🙂

### Current images 
screen shot 2017-06-08 at 4 16 26 pm

### Proposed images
screen shot 2017-06-08 at 4 16 31 pm

### CODE REVIEW

**Comment by insidegui** [comment]
Nice!

**Comment by insidegui** [comment]
@SoneeJohn Can you make a PR with just the images changed? This one contains calendar stuff...

**Comment by insidegui** [comment]
#235 is a duplicate of this one, right? Should I merge #235 and close this one?

**Comment by SoneeJohn** [comment]
@insidegui merge #235 and close this one :-)

**Comment by insidegui** [comment]
😉

**Pull request closed without merging**
