### PR TITLE
Support filtering on bookmarked sessions, some UI fixes for bookmarks in timeline

### PR DESCRIPTION
**Pull request by allenhumphreys**
Some general love to the annotation UI.

• Clicking anywhere else in the app will close the annotation window
• The white corners are no longer visible in the annotation window
• The annotation bubble highlighting is correctly removed after editing an annotation
• No longer receive bell when using escape or cmd + enter to exit an annotation
• Ability to filter by sessions with bookmarks on them

annotations

### CODE REVIEW

**Comment by insidegui** [comment]
This is great, I've been willing to do those fixes for a long time. Any idea as to why the CI failed? It's late and I'm going to bad, I'll have another look tomorrow.

**Comment by insidegui** [comment]
When you drag an annotation around and then release it, it opens up the annotation window, I think this should not happen (the window should only show up with a single, regular click).

Another issue is that when in fullscreen, pressing the esc key (which actually becomes an "exit from fullscreen" key in Touch Bar Macs) is exiting fullscreen instead of dismissing the annotation window. I think this could be solved by having the annotation window provide its own Touch Bar.

I'm pretty sure this is an issue that already existed before, but since you're working on this, maybe you can try to fix it :)

**Comment by allenhumphreys** [comment]
I can't get the window to appear after dragging the annotation around! Maybe I'm misunderstanding your description.

As for the touch bar issue, I'd like to fix it by always making the annotation window key instead of what currently happens
```
if annotation.isEmpty {
    annotationWindow.makeKeyAndOrderFront(nil)
} else {
    annotationWindow.orderFront(nil)
}
```

This will mean the text view will always become the first responder and it provides it's own touch bar. Doing this would also prevent possible other edge cases. Thoughts?

**Comment by insidegui** [comment]
Here's a gif showing the issue: 
issue


> This will mean the text view will always become the first responder and it provides it's own touch bar. Doing this would also prevent possible other edge cases. Thoughts?

Sounds good to me

**Comment by allenhumphreys** [comment]
Ooohhh, you have to drop it back where it started! I kept dropping it in new places.

**Comment by insidegui** [comment]
Also note the "overlapping timestamps from hell"

**Comment by allenhumphreys** [comment]
Now that you mention the timestamps, I think we should really move the time remaining and playback progress times to somewhere else. Since all that avoidance stuff that was done for the seek preview completely does not happen for annotations. We could move them to the ends of the timeline or below it? (Not part of this PR though, I woke up with a cold and now my brain is fuzzy)

**Comment by insidegui** [comment]
I really like the way the player looks with the labels where they are 😅

**Comment by allenhumphreys** [comment]
I do, too, actually. Maybe we can make their views owned by the timeline UI rather than the player, and then hide them when mousing over the timeline so the seek time preview and annotations can take precedence?

**Comment by insidegui** [comment]
That would make sense, yeah

**Comment by insidegui** [comment]
To avoid possible layout issues, maybe the timeline could delegate the hiding of the labels 🤔

**Comment by insidegui** [comment]
Something like `timelineViewTimePreviewLabelWillHitEdge(_ view: PUITimelineView)` and then the player can hide them

**Pull request merged**
