### PR TITLE
Swift4

### PR DESCRIPTION
**Pull request by otaviolima**
There are two commits in this PR, the first one removes ChromeCast support due I could not make it work with Swift 4 compiler yet. Once I get it to work rebase the PR and remove the commit.

One file that needs good attention is WWDCImageView the converted code only runs on OSX 10.13, I will review that again later but if someone has a good solution just tell me.

Filtering realm lists using blocks creates a ambiguous code, those were manually ported to NSPredicate when possible other were solved by assigning temporary variable.

There are lots of warnings to fix, which I will try to do either tomorrow or by the end of the week.

### CODE REVIEW

**Comment by otaviolima** [comment]
ChromeCast problem resolved in a fork of mine. So this branch is temporarily using my fork. 

Once https://github.com/insidegui/ChromeCastCore/pull/4 is either merged or solved in another way I will point back to original repo and rebase this branch.

**Comment by insidegui** [comment]
I merged your changes into a branch called `swift4` in ChromeCastCore, you can point Carthage to it for now 😉

**Comment by otaviolima** [comment]
`Cartfile` now points to correct repo using `swift4` branch.

I will now focus on `WWDCImageView` file. As mentioned earlier, the migration tool suggested API available only on OSX 10.13.

**Comment by otaviolima** [comment]
@insidegui PR is ready to be reviewed/tested.

**Comment by insidegui** [comment]
@otaviolima Thanks! Will do as soon as I can.

**Comment by otaviolima** [comment]
Fixes: https://github.com/insidegui/WWDC/issues/245

**Comment by insidegui** [comment]
@otaviolima Using a build from this branch, I was unable to switch between tabs. Turning on `@objc` inference fixed it. Can you update the PR enabling `@objc` inference?

screen shot 2017-09-24 at 09 53 50

**Comment by otaviolima** [comment]
Done.

I enabled that for all targets and I plan to disable it and fix any bug I/we find in another branch. As having it disabled is the recommended setting.

**Comment by insidegui** [comment]
Cool. Thanks!

**Pull request merged**
