### PR TITLE
Export Transcript

### LINKED ISSUE #631: Feature Request: Export Transcript
For translation and other purposes

### PR DESCRIPTION
**Pull request by subdan**
Add button for exporting transcript. 

Closes #631

### CODE REVIEW

**Comment by insidegui** [comment]
Hi @subdan, thanks for sending this in!

It works really well, I'd just like you to do a little adjustment to the layout. Here's a mockup of what I'd like it to look like:

image

It should be a fairly simple tweak, just change the order of items in the stack view and adjust the size of the export button.

**Comment by subdan** [comment]
Ok. I will do it on the next week. I am on a vacation ;-)

**Comment by subdan** [comment]
Done. 
image

Could you please add **hacktoberfest-accepted** label?

**Comment by bcmn** [comment]
This looks great 😍

**Comment by insidegui** [comment]
Perfect, thank you :)

**Pull request merged**
