### PR TITLE
Update project to Swift 4.1 Xcode 9.3

### PR DESCRIPTION
**Pull request by otaviolima**
I will be tracking the necessary work to get the project ready for Swift 4.1 and Xcode 9.3 here. 

Xcode 9.3 recommended configuration suggested that some warnings should be enabled, I did so and fixed some of the ObjC code, this change is not strictly necessary but does not break anything (At least should not). If modifying the ObjC code is not desirable let me know so I remove the commit.

Currently project is working fine for Xcode 9.3 beta 2.

### CODE REVIEW

**Comment by insidegui** [comment]
@otaviolima How are we doing on this? :)

**Comment by otaviolima** [comment]
Xcode 9.3 beta 4 introduced some new errors, taking a look on that.

Once I get it done, I will rebase and (force) push.

**Comment by otaviolima** [comment]
Checked with: Xcode 9.3 beta 4.

**Comment by allenhumphreys** [comment]
@otaviolima You need to switch the travis image to "xcode9.3beta", you can modify `.travis.yml` in this branch and it should take effect for the build. 

Also, I'm going to point this out right now: There will be some delay between when we are ready to merge this and when travis provides a non-beta Xcode 9.3 image. When that happens, we can either merge it and then fix it later, or wait until the image gets created before merging it.

**Comment by otaviolima** [comment]
Image updated.

Regarding @allenhumphreys I guess we can wait until the final image is provided.

**Comment by insidegui** [comment]
Yeah we should definitely wait for Xcode 9.3 to be released before merging this. About waiting for Travis, I'm not sure.

**Comment by otaviolima** [comment]
Rebased and updated.

Probably Travis will fail due not having the image, not sure.

**Comment by allenhumphreys** [comment]
Those build errors look confusing 🤔

**Comment by otaviolima** [comment]
They are indeed cryptic, could you try on your machine? Mine works fine™.

**Comment by allenhumphreys** [comment]
When travis doesn't recognize the image, it falls back to the default Xcode 8.3.3. You can probably remove 221f11c and change the image back to the beta. We can merge this in the mean time and change the image name when travis releases it.

screen shot 2018-03-31 at 8 08 19 am

**Comment by insidegui** [comment]
@otaviolima @allenhumphreys Let me know when it's safe to merge this without breaking Travis 😄

**Comment by otaviolima** [comment]
I personally don't want to use the beta image, so I think we can wait a bit more. But it is up to you.

**Comment by insidegui** [comment]
Let's wait

**Comment by allenhumphreys** [comment]
Waiting on https://github.com/travis-ci/travis-ci/issues/9416

**Comment by allenhumphreys** [comment]
@otaviolima @insidegui They've released the 9.3 image 💯. 

@otaviolima, I never meant to push my debugging changes directly to your branch, but I made a mistake with my git commands. Since I started, I went ahead and cleaned it up so that the bootstrap command produces verbose, formatted output for the Carthage builds. I definitely didn't want to re-write history on your branch, but you're more than welcome to squash my commits together if you want.

As a final follow up, were the changes in 221f11c necessary or were they meant to fix the failing build? I feel like if they're not necessary, they should be removed. Thoughts?

**Comment by otaviolima** [comment]
>As a final follow up, were the changes in 221f11c necessary or were they meant to fix the failing build? I feel like if they're not necessary, they should be removed. Thoughts?

I made it trying to fix the build (As it was complaining about Swift version not being set).

They are not strictly necessary, just a minor settings on project level that does not cause any harm of either being there or not being there. :)

**Comment by insidegui** [comment]
So is this safe to merge now? 😃

**Comment by otaviolima** [comment]
It is ;)

**Comment by insidegui** [comment]
🚀

**Pull request merged**
