### PR TITLE
disable "Featured" in the View menu until it's ready

### PR DESCRIPTION
**Pull request by mackuba**
It's kind of confusing what this item is supposed to do and why it doesn't do anything.

### CODE REVIEW

**Comment by insidegui** [comment]
We had to rush to get v6 out. The next version will already have the featured tab. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fernandocani** [comment]
In the Menu Bar, Edit, the "Featured" is there yet. Maybe it should hide for now.

**Comment by mackuba** [comment]
See above, it will be working soon :)

**Comment by insidegui** [comment]
Yeap, read above :)

**Pull request closed without merging**
